version: '3.1'

services:
  postgres:
    build:
      context: .
      dockerfile: DockerFile
    image: postgres:15.1-alpine
    container_name: task-2-postgresql-container
    restart: always
    environment:
      POSTGRES_USER: ilovebigdata
      POSTGRES_PASSWORD: andicannotlie
    ports:
      - '5432:5432'
    volumes: 
      - dbbiggy:/var/lib/postgresql/data
volumes:
    dbbiggy:
      external: false